# Generated by Django 5.2.7 on 2025-11-06 12:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': "Please enter the author's name.", 'max_length': 'Name cannot exceed 45 characters.', 'null': 'Name cannot be null.'}, max_length=45, validators=[django.core.validators.MinLengthValidator(4, message='Name must be at least 4 characters long.')], verbose_name='Name')),
                ('email', models.EmailField(error_messages={'blank': "Please enter the author's email.", 'invalid': 'Invalid email format.', 'null': 'Email cannot be null.'}, max_length=45, validators=[django.core.validators.EmailValidator(message='Please enter a valid email.')], verbose_name='Email')),
                ('occupation', models.CharField(error_messages={'blank': "Please provide the author's occupation.", 'max_length': 'Occupation cannot exceed 45 characters.', 'null': 'Occupation cannot be null.'}, max_length=45, validators=[django.core.validators.MinLengthValidator(4, message='Occupation must be at least 4 characters long.')], verbose_name='Occupation')),
                ('description', models.CharField(error_messages={'blank': 'Please provide a description for the author.', 'max_length': 'Description cannot exceed 300 characters.', 'null': 'Description cannot be null.'}, max_length=300, validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters long.')], verbose_name='Description')),
                ('picture', models.ImageField(error_messages={'blank': 'Please upload a picture for the author.', 'null': 'Picture cannot be null.'}, upload_to='authors', verbose_name='Picture')),
                ('user', models.OneToOneField(error_messages={'null': 'A user is required to create an author.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'author',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'Please enter the category title.', 'max_length': 'Category title cannot exceed 45 characters.', 'null': 'Category title cannot be null.'}, max_length=45, validators=[django.core.validators.MinLengthValidator(5, message='Category title must be at least 5 characters long.')])),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ['title'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('title',), name='unq_category_title', violation_error_message='This category is already registered.')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'Please enter the post title.', 'max_length': 'Title cannot exceed 45 characters.', 'null': 'Title cannot be null.'}, max_length=45, validators=[django.core.validators.MinLengthValidator(5, message='Title must be at least 5 characters long.')])),
                ('briefing', models.CharField(error_messages={'blank': 'Please enter the post briefing.', 'max_length': 'Briefing cannot exceed 100 characters.', 'null': 'Briefing cannot be null.'}, max_length=100, validators=[django.core.validators.MinLengthValidator(10, message='Briefing must be at least 10 characters long.')])),
                ('text', models.CharField(error_messages={'blank': 'Please enter the post text.', 'max_length': 'Text cannot exceed 3000 characters.', 'null': 'Text cannot be null.'}, max_length=3000, validators=[django.core.validators.MinLengthValidator(100, message='Text must be at least 100 characters long.')])),
                ('picture', models.ImageField(error_messages={'blank': 'Please upload an image for the post.', 'null': 'Post image cannot be null.'}, upload_to='posts')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, error_messages={'null': 'Creation date cannot be null.'})),
                ('updated_at', models.DateTimeField(blank=True, error_messages={'null': 'Update date cannot be null.'}, null=True)),
                ('author', models.ForeignKey(error_messages={'null': 'Author is required to create a post.'}, on_delete=django.db.models.deletion.CASCADE, to='cleanblog.author')),
                ('category', models.ForeignKey(error_messages={'null': 'Category is required to create a post.'}, on_delete=django.db.models.deletion.CASCADE, to='cleanblog.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('email',), name='unq_author_email', violation_error_message='This email is already registered.'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('updated_at__isnull', True), ('updated_at__gte', models.F('created_at')), _connector='OR'), name='chk_post_updated_at', violation_error_message='Update date cannot be earlier than creation date.'),
        ),
    ]
